<#
.SYNOPSIS
    SSH Proxy Exe Factory - 构建碎片化 SSH 代理 exe
.DESCRIPTION
    .\build.ps1 -TargetHost "YOUR_SERVER_IP" -User "root" -KeyPath "~\.ssh\YOUR_KEY_NAME" -Name "server1"
#>

param(
    [string]$Name = "ssh-proxy",
    [string]$TargetHost,
    [string]$User = "root",
    [string]$KeyPath
)

# ============================================================
# 读取 .env 文件
# ============================================================
if (Test-Path ".env") {
    Get-Content ".env" | Where-Object { $_ -match '^([^=]+)=(.*)$' } | ForEach-Object {
        $n, $v = $_.Split('=', 2)
        $n = $n.Trim()
        $v = $v.Trim()
        if (-not $PSBoundParameters.ContainsKey($n) -or -not $PSBoundParameters.$n) {
            Set-Variable -Name $n -Value $v -ErrorAction SilentlyContinue
        }
    }
}

# 后备：环境变量
if (-not $TargetHost) { $TargetHost = $env:TARGET_HOST }
if (-not $KeyPath) { $KeyPath = $env:SSH_KEY_PATH }

# ============================================================
# 验证
# ============================================================
if (-not $TargetHost -or -not $KeyPath) {
    Write-Host ""
    Write-Host " 错误: 缺少必需参数" -ForegroundColor Red
    Write-Host ""
    Write-Host " 用法: .\build.ps1 -TargetHost ""IP"" -KeyPath ""C:\path\to\key"" -Name ""server1""" -ForegroundColor White
    Write-Host ""
    exit 1
}

# ============================================================
# 字节数组分片
# ============================================================
function ConvertTo-Fragments {
    param([string]$Text, [int]$ChunkSize = 10)
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
    $result = @()
    for ($i = 0; $i -lt $bytes.Length; $i += $ChunkSize) {
        $end = [Math]::Min($i + $ChunkSize, $bytes.Length)
        $chunk = $bytes[$i..($end - 1)]
        $hex = ($chunk | ForEach-Object { "0x{0:X2}u8" -f $_ }) -join ", "
        $result += "[$hex]"
    }
    return $result
}

$keyFrags = ConvertTo-Fragments $KeyPath
$hostFrags = ConvertTo-Fragments $TargetHost
$userFrags = ConvertTo-Fragments $User

# ============================================================
# 生成 generated.rs
# ============================================================
$genContent = @"
// ============================================================
// DO NOT EDIT - Auto-generated by build.ps1
// Target: $User@$TargetHost -> $Name
// ============================================================

#![allow(dead_code)]

fn assemble(parts: &[&str]) -> String {
    let mut b = Vec::with_capacity(parts.iter().map(|p| p.len()).sum());
    for p in parts { b.extend_from_slice(p.as_bytes()); }
    String::from_utf8_lossy(&b).to_string()
}

pub fn get_key_path() -> String {
    assemble(&[$(($keyFrags | ForEach-Object { '"' + $_ + '"' }) -join ", ")])
}

pub fn get_host() -> String {
    assemble(&[$(($hostFrags | ForEach-Object { '"' + $_ + '"' }) -join ", ")])
}

pub fn get_user() -> String {
    assemble(&[$(($userFrags | ForEach-Object { '"' + $_ + '"' }) -join ", ")])
}
"@

$genContent | Out-File -FilePath "src\generated.rs" -Encoding UTF8

# ============================================================
# 确保 dist 目录存在
# ============================================================
if (-not (Test-Path "dist")) { New-Item -ItemType Directory -Path "dist" | Out-Null }

# ============================================================
# 编译
# ============================================================
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " SSH Proxy Exe Factory" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host " 配置:" -ForegroundColor Yellow
Write-Host "   名称: $Name" -ForegroundColor Green
Write-Host "   主机: $TargetHost" -ForegroundColor Green
Write-Host "   用户: $User" -ForegroundColor Green
Write-Host "   密钥: $KeyPath" -ForegroundColor Green
Write-Host ""

Write-Host " 编译中..." -ForegroundColor Yellow
cargo build --release -j 1 2>&1

if ($LASTEXITCODE -eq 0) {
    $srcExe = "target\release\ssh-proxy.exe"
    $dstExe = "dist\$Name.exe"

    if (Test-Path $srcExe) {
        Copy-Item $srcExe $dstExe -Force

        Write-Host ""
        Write-Host " 成功! 输出: dist\$Name.exe" -ForegroundColor Green
        Write-Host ""

        # 安全验证
        Write-Host " 安全验证:" -ForegroundColor Yellow
        $s = strings $srcExe 2>$null
        if ($s -match [regex]::Escape($TargetHost)) {
            Write-Host "   [警告] 主机地址在 strings 中可见" -ForegroundColor Red
        } else {
            Write-Host "   [OK] 主机地址已碎片化" -ForegroundColor Green
        }
        if ($s -match [regex]::Escape($KeyPath)) {
            Write-Host "   [警告] 密钥路径在 strings 中可见" -ForegroundColor Red
        } else {
            Write-Host "   [OK] 密钥路径已碎片化" -ForegroundColor Green
        }

        Write-Host ""
        Write-Host " 使用:" -ForegroundColor Yellow
        Write-Host "   dist\$Name.exe ""whoami""      # 执行命令" -ForegroundColor White
        Write-Host "   dist\$Name.exe ""docker ps""   # 查看容器" -ForegroundColor White
        Write-Host "   dist\$Name.exe                 # 交互式 SSH" -ForegroundColor White
        Write-Host ""
    }
} else {
    Write-Host " 编译失败!" -ForegroundColor Red
    exit 1
}
